### ISSUE TITLE
Need to check geonode harvesting with SSL

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#770]
GeoNode integration server was migrated to use SSL => check harvesting still works with https://int.geonode-gfdrrlab.org/api/ before switching geonode production to SSL

**Comment by fvanderbiest** [comment]
From http://int.thinkhazard.org/ ?

**Comment by fvanderbiest** [comment]
From dev:
```
INFO     Continue with documents
INFO     Retrieving https://int.geonode-gfdrrlab.org/api/documents/
ERROR    Traceback (most recent call last):
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/thinkhazard/processing/harvesting.py", line 117, in do_execute
    self.harvest_documents()
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/thinkhazard/processing/harvesting.py", line 230, in harvest_documents
    documents = self.fetch('documents')
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/thinkhazard/processing/harvesting.py", line 134, in fetch
    response, content = h.request(url)
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
SSLHandshakeError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by fvanderbiest** [comment]
@saimon can you `sudo update-ca-certificates` on `wb-thinkhazard-dev-1.sig.cloud.camptocamp.net` ?
We need support for let'sencrypt certificates for python httplib2 from wheezy. Thanks.

**Comment by fvanderbiest** [comment]
Oops, sorry @Saimon I meant @saimonn !

**Comment by saimonn** [comment]
Done, but didn't update any cert, was that the expected result ?
``` 
$ ssh -lroot wb-thinkhazard-dev-1.sig.cloud.camptocamp.net update-ca-certificates
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
done.
done.
```

**Comment by Vampouille** [comment]
Curl has not SSL issue :
```
* Connected to int.geonode-gfdrrlab.org (54.246.242.223) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: CN=int.geonode-gfdrrlab.org
* 	 start date: 2017-06-01 15:05:00 GMT
* 	 expire date: 2017-08-30 15:05:00 GMT
* 	 subjectAltName: int.geonode-gfdrrlab.org matched
* 	 issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
* 	 SSL certificate verify ok.
```

**Comment by Vampouille** [comment]
Fixed by https://github.com/GFDRR/thinkhazard/pull/769/commits/b44185866b40a80cf7d9141bf141b38c7105e8c9

**Comment by Vampouille** [comment]
Tested from TH int to geonode int. It's working with SSL and api key, just somes warning:
```
$ make harvest
...
INFO       Updating Region - Zimbabwe
WARNING  AdminUnit code 40781 is not in our GAUL dataset
INFO     Cleaning previous data
...
WARNING  dataset 987: data_update_date is empty
...
WARNING  document 461: hazard_type not supported: none
...
WARNING  document 496: hazard_type not supported: wind_storm
WARNING  document 1010: hazard_type not supported: Drought
WARNING  document 963: hazard_type not supported: Volcano
WARNING  document 1008: hazard_type not supported: Flood
WARNING  document 760: hazard_type not supported: coastal_erosion
WARNING  document 679: hazard_type not supported: soil_erosion
```
```
$ make complete
WARNING  Hazardset CF-COM-SWIO incomplete: No layer for level HIG
...
WARNING  Hazardset EQ-MEX-ERN incomplete: No associated regions
```

**Comment by fvanderbiest** [comment]
> just some warnings

These are normal warnings, go ahead.

**Comment by fjacon** [comment]
@fvanderbiest @Vampouille : should we close this issue ?
