### ISSUE TITLE
Memory error while processing FL-GLOBAL-SSBN-32bit

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard#784]
```
INFO     FL-GLOBAL-SSBN-32bit
INFO       Cleaning previous outputs
INFO       Opening raster files
INFO       Iterating over 38168 administrative divisions
INFO       ... processed 10%
INFO       ... processed 20%
INFO       ... processed 30%
INFO       ... processed 40%
INFO       ... processed 50%
INFO       ... processed 60%
INFO       ... processed 70%
INFO       ... processed 80%
INFO       ... processed 90%
ERROR    Processing of div. 4375 failed
Traceback (most recent call last):
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/thinkhazard/processing/processing.py", line 227, in create_outputs
    hazardlevel = self.preprocessed_hazardlevel(shape)
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/thinkhazard/processing/processing.py", line 294, in preprocessed_hazardlevel
    if value in data:
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/numpy/ma/core.py", line 3783, in __eq__
    check = self.filled(0).__eq__(other)
  File "/srv/apache/wb-thinkhazard/private/thinkhazard/.build/venv/local/lib/python2.7/site-packages/numpy/ma/core.py", line 3592, in filled
    result = self._data.copy('K')
MemoryError
INFO       Closing raster files
```

**Comment by stufraser1** [comment]
This data set is to be removed. It was established as too large to process (we have a smaller version of the data that works in TH!). However, we've been unable to delete it in UI, and via sftp as access not working -being dealt with in other issues. 
Also to delete (all layers in geonode named 'delete')
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_fu_v3_4bit
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_fu_raster_v3
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_uu_raster_v5
https://www.geonode-gfdrrlab.org/layers/hazard:adm2_uu_v5_4bit

**Comment by fvanderbiest** [comment]
I've just deployed a fix to production, which restores the ability to delete & modify layers.

**Comment by stufraser1** [comment]
Confirmed deleting via UI works now. Closing
